added animations to page sections
/pages/Products/lms/section/Studentfeatures.tsx
error: could not apply 063d826... added animations to page sections
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 063d826... added animations to page sections
PS D:\CoireiWeb> git status
interactive rebase in progress; onto 90cb101
Last command done (1 command done):
   pick 063d826 added animations to page sections
No commands remaining.
You are currently rebasing branch 'main' on '90cb101'.
  (fix conflicts and then run "git rebase --continue")
  (use "git rebase --skip" to skip this patch)
  (use "git rebase --abort" to check out the original branch)

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        new file:   src/assets/images/products/1.svg
        new file:   src/assets/images/products/2.svg
        new file:   src/assets/images/products/3.svg
        new file:   src/assets/images/products/4.svg
        new file:   src/assets/images/products/staticbgglobal.svg
        modified:   src/pages/Products/Follei/pages/SDRWorker/section/FirstResponse.tsx
.git/COMMIT_EDITMSG [unix] (10:47 08/07/2026)           #